version: '3.3'
services:
  cache:
    container_name: redis-flip
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  db:
    container_name: mysql-flip
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flip_assignment'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
# network:
#   default:
#     external:
#       name: localdb